In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.head()

    mpg  cylinders cubicinches   hp weightlbs  time-to-60  year     brand
0  14.0          8         350  165      4209          12  1972       US.
1  31.9          4          89   71      1925          14  1980   Europe.
2  17.0          8         302  140      3449          11  1971       US.
3  15.0          8         400  150      3761          10  1971       US.
4  30.5          4          98   63      2051          17  1978       US.

In [6]:
df.shape

(261, 8)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 8 columns):
mpg            261 non-null float64
cylinders      261 non-null int64
cubicinches    261 non-null object
hp             261 non-null int64
weightlbs      261 non-null object
time-to-60     261 non-null int64
year           261 non-null int64
brand          261 non-null object
dtypes: float64(1), int64(4), object(3)
memory usage: 16.4+ KB

In [5]:
df.describe()

              mpg   cylinders          hp  time-to-60         year
count  261.000000  261.000000  261.000000  261.000000   261.000000
mean    23.144828    5.590038  106.360153   15.547893  1976.819923
std      7.823570    1.733310   40.499959    2.910625     3.637696
min     10.000000    3.000000   46.000000    8.000000  1971.000000
25%     16.900000    4.000000   75.000000   14.000000  1974.000000
50%     22.000000    6.000000   95.000000   16.000000  1977.000000
75%     28.800000    8.000000  138.000000   17.000000  1980.000000
max     46.600000    8.000000  230.000000   25.000000  1983.000000

In [13]:
# separando dados de entrada e labels
entrada = df.iloc[:, 1:6].values
saida = df.iloc[:, 0:1].values

array([[14. ],
       [31.9],
       [17. ],
       [15. ],
       [30.5],
       [23. ],
       [13. ],
       [14. ],
       [25.4],
       [37.7],
       [34. ],
       [34.3],
       [16. ],
       [11. ],
       [19.1],
       [16.9],
       [31.8],
       [16. ],
       [24. ],
       [24. ],
       [37.2],
       [21.5],
       [24. ],
       [15.5],
       [38.1],
       [33. ],
       [31. ],
       [14. ],
       [18. ],
       [29.9],
       [27. ],
       [16. ],
       [23. ],
       [21. ],
       [30. ],
       [22.4],
       [26. ],
       [21.5],
       [16.5],
       [20.2],
       [16. ],
       [14. ],
       [18.5],
       [17.5],
       [14. ],
       [31.6],
       [13. ],
       [22. ],
       [29. ],
       [20.2],
       [13. ],
       [27.2],
       [14. ],
       [24. ],
       [16.5],
       [16. ],
       [19. ],
       [33.5],
       [29. ],
       [13. ],
       [18. ],
       [22. ],
       [32.7],
       [46.6],
       [14. ],
       [18.5],
       [26. ],
       [32. ],
       [29.5],
       [17.5],
       [20. ],
       [27. ],
       [28. ],
       [24. ],
       [29. ],
       [38. ],
       [22.5],
       [21.1],
       [26. ],
       [32.4],
       [15.5],
       [12. ],
       [19.2],
       [23. ],
       [25. ],
       [35. ],
       [18. ],
       [17.6],
       [28. ],
       [31. ],
       [34.1],
       [27.2],
       [13. ],
       [17. ],
       [26. ],
       [17. ],
       [12. ],
       [18. ],
       [18.2],
       [16. ],
       [11. ],
       [12. ],
       [25. ],
       [34.2],
       [32.2],
       [26.6],
       [43.4],
       [30. ],
       [25. ],
       [18. ],
       [20. ],
       [18. ],
       [16. ],
       [33. ],
       [37.3],
       [18. ],
       [24.5],
       [21. ],
       [34.4],
       [15. ],
       [27. ],
       [26. ],
       [16. ],
       [23.2],
       [27. ],
       [26.5],
       [13. ],
       [30.9],
       [20. ],
       [36.1],
       [26. ],
       [28. ],
       [12. ],
       [17. ],
       [15. ],
       [16. ],
       [26. ],
       [13. ],
       [22. ],
       [21. ],
       [26.8],
       [29. ],
       [32. ],
       [35.1],
       [19.2],
       [23. ],
       [20.6],
       [27. ],
       [15. ],
       [18.1],
       [31.3],
       [27.5],
       [14. ],
       [15. ],
       [28. ],
       [19. ],
       [18. ],
       [29.5],
       [19. ],
       [16.2],
       [24.3],
       [17.5],
       [18. ],
       [23. ],
       [23. ],
       [19.9],
       [16. ],
       [26. ],
       [20. ],
       [38. ],
       [32.4],
       [20.3],
       [29. ],
       [31. ],
       [21. ],
       [26. ],
       [14. ],
       [14. ],
       [20.2],
       [31.5],
       [19.8],
       [33.8],
       [17.5],
       [18. ],
       [34. ],
       [20.8],
       [18. ],
       [13. ],
       [14. ],
       [13. ],
       [25.8],
       [28.4],
       [13. ],
       [15. ],
       [14. ],
       [41.5],
       [27.2],
       [43.1],
       [29. ],
       [33.5],
       [26. ],
       [23. ],
       [23.9],
       [19. ],
       [21. ],
       [15. ],
       [40.8],
       [18. ],
       [13. ],
       [25.4],
       [22. ],
       [17.7],
       [39.1],
       [30. ],
       [22. ],
       [32.9],
       [37. ],
       [14.5],
       [28.8],
       [15. ],
       [17.5],
       [21.6],
       [14. ],
       [16.5],
       [14. ],
       [32. ],
       [10. ],
       [31. ],
       [21. ],
       [27. ],
       [15. ],
       [28. ],
       [23. ],
       [16. ],
       [20. ],
       [44. ],
       [14. ],
       [20.2],
       [39. ],
       [23. ],
       [13. ],
       [18. ],
       [16. ],
       [25. ],
       [14. ],
       [15. ],
       [19.4],
       [44.3],
       [28. ],
       [29. ],
       [32.1],
       [24. ],
       [36.4],
       [13. ],
       [23.5],
       [24. ],
       [17. ],
       [36.1],
       [22. ],
       [18. ],
       [22. ]])

In [14]:
# dividindo em treino e teste
# Train Test Split
from sklearn.model_selection import train_test_split

# aplicando a funcao train_test_split para separar os conjuntos de treino e teste segundo uma porcentagem de separação definida. 
train_data, test_data, train_labels, test_labels = train_test_split(entrada, saida, test_size = 0.30, random_state = 42)

In [18]:
train_data

array([[8, '305', 145, '3880', 13],
       [8, '302', 140, '3449', 11],
       [4, '151', 90, '2735', 18],
       [6, '231', 110, '3039', 15],
       [4, '107', 86, '2464', 16],
       [4, '112', 88, '2395', 18],
       [6, '250', 88, '3302', 16],
       [4, '121', 110, '2660', 14],
       [6, '225', 95, '3785', 19],
       [4, '98', 65, '2380', 21],
       [4, '135', 84, '2490', 16],
       [8, '400', 175, '4385', 12],
       [8, '350', 175, '4100', 13],
       [4, '90', 48, '2085', 22],
       [8, '350', 125, '3900', 17],
       [6, '156', 108, '2930', 16],
       [8, '318', 150, '3399', 11],
       [4, '140', 78, '2592', 19],
       [4, '97', 54, '2254', 24],
       [6, '250', 98, '3525', 19],
       [8, '267', 125, '3605', 15],
       [4, '72', 69, '1613', 18],
       [4, '83', 61, '2003', 19],
       [4, '86', 64, '1875', 16],
       [6, '250', 100, '3278', 18],
       [8, '302', 140, '4141', 14],
       [6, '231', 110, '3415', 16],
       [6, '250', 78, '3574', 21],
       [6, '250', 110, '3645', 16],
       [4, '140', 72, '2565', 14],
       [4, '121', 115, '2671', 14],
       [4, '98', 65, '2045', 16],
       [6, '200', 81, '3012', 18],
       [8, '305', 140, '4215', 13],
       [6, '250', 100, '3329', 16],
       [4, '98', 68, '2045', 19],
       [8, '429', 198, '4341', 10],
       [4, '141', 71, '3190', 25],
       [8, '351', 149, '4335', 15],
       [4, '90', 48, '1985', 22],
       [6, '231', 110, '3907', 21],
       [8, '455', 225, '4425', 10],
       [8, '350', 145, '3988', 13],
       [6, '232', 90, '3085', 18],
       [8, '302', 140, '4638', 16],
       [4, '85', 70, '1945', 17],
       [4, '96', 69, '2189', 18],
       [4, '98', 90, '2265', 16],
       [6, '171', 97, '2984', 15],
       [4, '71', 65, '1773', 19],
       [4, '113', 95, '2372', 15],
       [6, '225', 110, '3360', 17],
       [8, '350', 165, '4209', 12],
       [6, '231', 165, '3445', 13],
       [8, '400', 150, '4997', 14],
       [4, '85', 65, '1975', 19],
       [6, '200', 85, '3070', 17],
       [8, '318', 135, '3830', 15],
       [4, '97', 46, '1835', 21],
       [4, '108', 94, '2379', 17],
       [4, '68', 49, ' ', 20],
       [8, '350', 165, '3693', 12],
       [4, '97', 78, '2188', 16],
       [6, '232', 112, '2835', 15],
       [6, '168', 116, '2900', 13],
       [8, '351', 148, '4657', 14],
       [8, '350', 145, '4082', 13],
       [4, '98', 63, '2051', 17],
       [8, '400', 170, '4668', 12],
       [4, '120', 97, '2506', 15],
       [8, '260', 110, '3365', 16],
       [4, '91', 60, '1800', 16],
       [4, '121', 98, '2945', 15],
       [6, '168', 132, '2910', 11],
       [8, '318', 150, '4190', 13],
       [4, '114', 91, '2582', 14],
       [8, '350', 145, '4055', 12],
       [4, '116', 75, '2246', 14],
       [6, '198', 95, '3102', 17],
       [4, '120', 79, '2625', 19],
       [8, '318', 150, '4237', 15],
       [8, '455', 225, '3086', 10],
       [8, '400', 190, '4422', 13],
       [3, '70', 90, '2124', 14],
       [6, ' ', 105, '3897', 19],
       [4, '156', 105, '2745', 17],
       [6, '250', 72, '3158', 20],
       [8, '351', 142, '4054', 14],
       [4, '90', 70, '1937', 14],
       [8, '318', 150, '4077', 14],
       [8, '429', 198, '4952', 12],
       [6, '232', 90, '3265', 18],
       [6, '258', 95, '3193', 18],
       [4, '122', 86, '2395', 16],
       [4, '98', 79, '2255', 18],
       [4, '140', 83, '2639', 17],
       [8, '318', 140, '4080', 14],
       [6, '250', 110, '3520', 16],
       [4, '120', 88, '2957', 17],
       [4, '97', 67, '2145', 18],
       [8, '400', 150, '3761', 10],
       [4, '151', 84, '2635', 16],
       [4, '116', 75, '2158', 16],
       [8, '304', 150, '3672', 12],
       [6, '225', 105, '3121', 17],
       [4, '140', 72, '2401', 20],
       [8, '318', 140, '3735', 13],
       [6, '200', 88, '3060', 17],
       [6, '198', 95, '2904', 16],
       [8, '400', 190, '4325', 12],
       [4, '97', 67, '1985', 16],
       [8, '351', 152, '4215', 13],
       [8, '440', 215, '4312', 9],
       [5, '131', 103, '2830', 16],
       [8, '318', 150, '4457', 14],
       [4, '97', 88, '2279', 19],
       [4, '119', 97, '2300', 15],
       [4, '115', 95, '2694', 15],
       [8, '318', 150, '4096', 13],
       [8, '400', 180, '4220', 11],
       [4, '119', 82, '2720', 19],
       [5, '183', 77, '3530', 20],
       [8, '350', 180, '3664', 11],
       [8, '360', 175, '3821', 11],
       [6, '200', 85, '2587', 16],
       [4, '151', 90, '2678', 17],
       [8, '304', 150, '3433', 12],
       [6, '225', 105, '3439', 16],
       [4, '97', 92, '2288', 17],
       [8, '318', 150, '4498', 15],
       [8, '350', 145, '4440', 14],
       [4, '119', 100, '2615', 15],
       [8, '454', 220, '4354', 9],
       [4, '86', 65, '2110', 18],
       [8, '350', 180, '4380', 12],
       [4, '88', 76, '2065', 15],
       [8, '400', 150, '4464', 12],
       [8, '360', 215, '4615', 14],
       [4, '122', 86, '2226', 17],
       [6, '168', 120, '3820', 17],
       [8, '440', 215, '4735', 11],
       [6, '225', 90, ' ', 19],
       [6, '250', 88, '3021', 17],
       [4, '130', 102, '3150', 16],
       [8, '302', 130, '4295', 15],
       [4, '105', 63, '2125', 15],
       [4, '90', 70, '1937', 14],
       [6, '173', 115, '2595', 11],
       [4, '97', 78, '1940', 15],
       [4, '90', 75, '2125', 15],
       [4, '121', 110, '2600', 13],
       [4, '98', 83, '2075', 16],
       [6, '225', 100, '3630', 18],
       [4, '151', 90, '3003', 20],
       [8, '305', 130, '3840', 15],
       [8, '318', 150, '3940', 13],
       [4, '151', 90, '2670', 16],
       [4, '98', 66, '1800', 14],
       [3, '80', 110, '2720', 14],
       [4, '98', 68, '2135', 17],
       [4, '97', 52, '2130', 25],
       [4, '135', 84, '2525', 16],
       [4, '89', 71, '1925', 14],
       [8, '340', 160, '3609', 8],
       [8, '302', 139, '3205', 11],
       [4, '97', 78, '2300', 15],
       [4, '134', 95, '2560', 14],
       [4, '105', 70, '2200', 13],
       [6, '250', 100, '3781', 17],
       [4, '151', 88, '2740', 16],
       [6, '225', 85, '3465', 17],
       [8, '260', 90, '3420', 22],
       [4, '98', 83, '2219', 17],
       [6, '225', 100, '3233', 15],
       [6, '146', 97, '2815', 15],
       [4, '79', 67, '1963', 16],
       [6, '250', 105, '3353', 15],
       [4, '86', 65, '2019', 16],
       [8, '351', 153, '4129', 13],
       [4, '112', 88, '2640', 19],
       [4, '90', 48, '2335', 24],
       [4, '98', 80, '2126', 17]], dtype=object)

In [15]:
# realiza o processo de normalização dos dados
from sklearn.preprocessing import StandardScaler
normaliza = StandardScaler()  #objeto que normaliza os dados
normaliza.fit(train_data)  #realiza a normalização dos dados

X_train = normaliza.transform(train_data)
X_test = normaliza.transform(test_data)

ValueError: could not convert string to float: